format = """
$username\
$hostname\
$directory\
$localip\
$os\
\n$character"""

right_format = """
$cmd_duration\
$git_branch\
$git_status\
$time"""

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
style = "cyan"  # Cyan is still vibrant but not as harsh as brighter colors
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = '󰌾'
read_only_style = 'red'  # Bright red for read-only status

[git_branch]
format = "[$branch]($style)"
style = "bright-black"  # Still allows visibility but less harsh
symbol = " "

[git_status]
format = "($ahead_behind) $stashed ($style)"
style = "cyan"  # Cyan is bright but works well for visibility without being overly bright
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"  # Dimmed state color to reduce harshness

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
ssh_symbol = " "

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

[os]
format = "on [($type $symbol )]($style)"
style = "bold blue"  # Bold blue to keep things distinct without too much intensity
disabled = false

[python]
format = "[$virtualenv]($style) "
style = "bright-black"  # A softer bright-black style for Python environments
symbol = " "

[time]
disabled = false
style = 'black'
format = '[  $time ]($style) '
use_12hr = true

[username]
style_user = 'white bold'  # Bold white for user
style_root = 'black bold'  # Bold black for root user
format = 'user: [$user]($style) '
disabled = false
show_always = false


##symbols that could be used
[aws]
symbol = "  "
[buf]
symbol = " "
[c]
symbol = " "
[conda]
symbol = " "
[crystal]
symbol = " "
[dart]
symbol = " "
[docker_context]
symbol = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[fennel]
symbol = " "
[fossil_branch]
symbol = " "
[golang]
symbol = " "
[guix_shell]
symbol = " "
[haskell]
symbol = " "
[haxe]
symbol = " "
[hg_branch]
symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[kotlin]
symbol = " "
[lua]
symbol = " "
[memory_usage]
symbol = "󰍛 "
[meson]
symbol = "󰔷 "
[nim]
symbol = "󰆥 "
[nix_shell]
symbol = " "
[nodejs]
symbol = " "
[ocaml]
symbol = " "
[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
[package]
symbol = "󰏗 "
[perl]
symbol = " "
[php]
symbol = " "
[pijul_channel]
symbol = " "
[rlang]
symbol = "󰟔 "
[ruby]
symbol = " "
[rust]
symbol = " "
[scala]
symbol = " "
[swift]
symbol = " "
[zig]
symbol = " "
